### ISSUE TITLE
[FEATURE] Command Block

### ISSUE THREAD

**Issue by EddieJ5** [GorilloCraft/Server#104]
Permissions to use command blocks in StaffWorld

**Comment by ItsMeGriff** [comment]
We normally do not like to enable command blocks within any server and it is not possible to just enable it within certain worlds. This is because command blocks can run any command and bypass all permissions.

**Comment by EddieJ5** [comment]
I'm lost on the reasoning for this, if by permissions you means Helpers/Mods getting equivalent to Admin/Owner perms with the blocks? Or if you mean by players getting them then couldn't the perms for using them be limited to just staff ranks?

**Comment by ItsMeGriff** [comment]
> I'm lost on the reasoning for this, if by permissions you means Helpers/Mods getting equivalent to Admin/Owner perms with the blocks? Or if you mean by players getting them then couldn't the perms for using them be limited to just staff ranks?

Basically command blocks have “owner” privilege meaning that anyone can run any command through them. Think of command blocks as a yes or no option. What this means is if you have access to command blocks then YES you can run any command on the server. But if you don’t have access to command blocks then NO you you can’t run any commands. So if I were to enable command blocks there is no way for staff to regulate who gets to use certain command blocks and what commands are run through it. The reason they are disabled by default on all servers is because of this reason because anyone can get a command block and give themselves full OP permissions. 

Not sure if that cleared it up. Command blocks are pretty complicated from the admin perspective and it is just easier to have them disabled.
