### ISSUE TITLE
[BUG] FISHING LEADERBOARD BROKEN

### ISSUE THREAD

**Issue by foodbandit** [GorilloCraft/Server#113]
**Describe the bug**
(Originally mentioned by Zone in the bug reporting channel on discord on July 17) It seems that the fishing leaderboard resets daily instead of monthly.

**To Reproduce**
1. Go to spawn leaderboards

**Expected behavior**
Leaderboard keeps records of fishing catches throughout one month period.

**Screenshots**
![image](https://user-images.githubusercontent.com/109165139/185045335-d6f5fdf7-8d6f-4081-ba3f-a14b99225ec3.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
Maybe it would be easier to just change the title to (Daily) instead of (Monthly). Then again, maybe it would engage players more if it were monthly based. Not sure.

**Comment by ImSnipper** [comment]
I think it should be an easy fix to properly track monthly. 

But, changing the title to "Daily" is also an option.

Which do you guys prefer?

**Comment by MelodyMcKenna** [comment]
My opinion: monthly would be best for this type of leader board.

**Comment by ImSnipper** [comment]
So, it turns out the fishing statistic is only tracked hourly, daily, weekly, and yearly.

I've updated the statistic to track weekly on the leaderboard. If we believe weekly is not a viable option for this type of leaderboard, we can change the leaderboard to something all together. Feel free to post your suggestions in Discord!
