### ISSUE TITLE
[FEATURE] Ban Duration Shown on Disconnected Screen

### ISSUE THREAD

**Issue by Gallix18** [GorilloCraft/Server#115]
Would like users to be able to see the duration of their ban/tempban on the screen they get with their failed log-in. Currently the screen only shows their reason for the ban but not the duration. 
![image](https://user-images.githubusercontent.com/108558492/185284432-da5f1027-6340-4d31-b4cf-2d1bea465c38.png)

**Comment by Gallix18** [comment]
In the case of the above photo the ban duration was 1 day but was not shown on the login attempt

**Comment by ImSnipper** [comment]
I'm thinking this might be an issue with Bedrock not displaying the full ban message. Temporary bans should include the duration on the ban screen...can someone try testing this on Java to see if the ban duration displays?

```
banned_message: "&b&lGorillo&f&lCraft&f&r\n&r \n&bYour account has been banned because\
  \ of\n&f$reason\n&r \n&bDate: &f$dateStart\n&bExpires in: &f$duration\n&r \n&7You\
  \ may appeal your ban in our Discord\n&a&ndiscord.gg/gorillo"
```
^ Is the ban message for temporary bans.

**Comment by ImSnipper** [comment]
![unknown](https://user-images.githubusercontent.com/26206574/185542745-6af1da77-4005-4037-a143-f13e36101af8.png)

I just banned Melody for 1 day as a test (She is on Java) and it displayed the ban duration, and additional information.

I'm curious, are you able to click on the three little dots when on Bedrock?

**Comment by ImSnipper** [comment]
It looks like these is a limitation within Bedrock, and something that we cannot easily fix. I am going to reach out to the developer of LiteBans though, and see if there is some different way of displaying the ban message, so that the entire message displays.

In the meantime, I'd recommend typing the ban duration for Bedrock users in the message:
Example: /ban Snipper 7d Inappropriate Behavior (7 Day Ban)
