### ISSUE TITLE
[FEATURE] Add @here and @everyone to filtered words

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#40]
**Please describe the feature you think should be implemented**
Add @here and @everyone to be filtered as if it was a swear word so it doesn't show in chat, therefore we won't receive pings through the Discord in-game chat channel

**Comment by ItsMeGriff** [comment]
@GorilloYT please remove the bots permission to use @here and @everyone in your discord

**Comment by Gallix18** [comment]
I disabled the admin permissions the bot requested and suppressed pinging of @here, @everyone and role pings. The bot continues to be responsive in the appropriate channels and has successfully suppressed an @here ping since the permission changes. This issue can be marked as resolved if there’s nothing else.

**Comment by ItsMeGriff** [comment]
> I disabled the admin permissions the bot requested and suppressed pinging of @here, @everyone and role pings. The bot continues to be responsive in the appropriate channels and has successfully suppressed an @here ping since the permission changes. This issue can be marked as resolved if there’s nothing else.

Thanks! Closing issue
