### ISSUE TITLE
[BUG] WEEK 4 PREMIUM CHALLENGE: Love Tap

### ISSUE THREAD

**Issue by foodbandit** [GorilloCraft/Server#90]
**Describe the bug**
The challenge Love Tap's description is: "To complete this challenge, you must deal 1 heart of damage to 5 players". I completed the challenge by killing (consensually) one player in one instance.

**To Reproduce**
1. Read Week 4 Premium: Love Tap description.
2. Use /pvp on
3. Kill one player (deal minimum 5 hearts of damage)

**Expected behavior**
You would need to deal 1 heart damage to 5 seperate players, rather than 5 hearts to 1 player.

**Screenshots**
Video footage in #s2-bug-reporting channel in Discord.

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
N/A

**Comment by ImSnipper** [comment]
For some odd reason, the plugin we are using for challenges does not have a feature to require 5 unique players. Unfortunately, this challenge will have to remain as is. I don't think it's a significant issue, since it's a premium challenge and not many players will be completing it.

Perhaps we could update the description to say "Deal 5 hearts of damage to a player" or something...

Thanks for reporting!
