### ISSUE TITLE
[FEATURE] Boats In The Shopping District

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#98]
**Please describe the feature you think should be implemented**
Players are placing boats in their shop plots and rowing them out onto the main areas where people, including staff, cannot remove or enter them. Can we please disable boats in the shopping district to prevent this?

**Comment by ImSnipper** [comment]
I have disabled boats from being placed by players who are NOT the owner of a plot..

Unfortunately, it seems there isn't a way within world guard to prevent boats from being placed by plot OWNERS. It seems this isn't as significant of an issue any more (I haven't seen a boat in the shopping district since your original suggestion).

If it happens, please let an admin/dev know and we'll take care of it. If it becomes an issue, I'll see if Griff can write a plugin to prevent the placement of particular blocks in a world, regardless of world guard group ownership
